# DATABASE
spring:
  datasource:
    # ??? ?? ? ???? ????. Database? H2? ??? ?? ??
    driver-class-name: org.h2.Driver
    # ?????? ??? ?? ??
    url: jdbc:h2:~/test
    # ???? (??? : sa)
    username: sa
    # ?? ?? ??? ????? ???? ?? x
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      # H2 ??? ?? ??/???
      enabled: true
      # ?? ??? ?? url ??
      path: /console
